### ISSUE TITLE
Patches

### ISSUE THREAD

**Issue by onox** [dany93/p51d-modifs#1]
Hi @dany93 

Could you perhaps import the p51d in a commit and then add yours and efel's patches in a second commit? I'm having troubles with mediafire :sob:

**Comment by dany93** [comment]
Hi @onox 

That was my first idea. But github refused it, because some files makes more than 100 MB. At least one, as indicated

```
dany@dellinux ~/FG/github/p51d $ git push
Username for 'https://github.com': dany93
Password for 'https://dany93@github.com': 
Counting objects: 745, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (741/741), done.
Writing objects: 100% (744/744), 536.85 MiB | 586.00 KiB/s, done.
Total 744 (delta 121), reused 0 (delta 0)
remote: warning: File Resources/WIP/wingTip.tif is 50.07 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: 6d5bea1491948c5e75d5f60e1cb4fed3
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File Resources/WIP/fus-texture.xcf is 129.65 MB; this exceeds GitHub's file size limit of 100.00 MB
To https://github.com/dany93/p51d-modifs.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: impossible de pousser des références vers 'https://github.com/dany93/p51d-modifs.git'
```

But fus-texture.xcf is only for GIMP, true? Not read by FG ?
I'm tempted to try again by removing /fus-texture.xcf.
A fus-texture.png seems to be the useful file for the .ac.
Hoping that there are not too many like this...

I would not like having to install this  Git Large File Storage.

**Comment by onox** [comment]
> I would not like having to install this Git Large File Storage.

~~Why not? You can put all those files in `Resources/` in LFS. Then your main repo should be much smaller~~

`.xcf` is GIMP.

~~Or just simply remove the whole `Resources/` folder.~~

**Comment by onox** [comment]
`.xcf` is GIMP.

**Comment by onox** [comment]
Or just simply remove the whole `Resources/` folder.

**Comment by onox** [comment]
It seems there's already a discussion going on in the forums. Maybe the best thing is to make sure your patches get added to FGAddon. The aircraft is already there anyway.

**Comment by dany93** [comment]
@onox wrote

> Could you perhaps import the p51d in a commit and then add yours and efel's patches in a second commit?

Done. Initial FG Rep version p51d_20141227 (engine does not start), then efel's Autostart patch + my changes.
https://github.com/dany93/p51d-modifs

[This discussion](http://forum.flightgear.org/viewtopic.php?f=4&t=28279)?
